### ISSUE TITLE
componentPrepare 并不能执行

### ISSUE THREAD

**Issue by qazse1234567** [lnlfps/symph-joy#1]

**Comment by lnlfps** [comment]
examples/basic示例项目里，有`componentPrepare`的使用示例。需要注意的是`componentPrepare`方法只有`@controller`类的Component才会执行。

**Comment by qazse1234567** [comment]
@lnlfps 解决了

**Comment by lnlfps** [comment]
在后续的版本中，确实发现有可能导致`componentPrepare`方法无法执行的问题，在0.5.0以后的版本中已经修复。
