### ISSUE TITLE
用<Link>跳转到新的路由，无法执行componentPrepare方法，重新刷新后才能执行

### ISSUE THREAD

**Issue by qazse1234567** [lnlfps/symph-joy#2]

**Comment by lnlfps** [comment]
在浏览器上跳转新路由，使用的是浏览器本地路由，新页面中的`componentPrepare `方法，将只在浏览器上运行，不会启动服务端渲染流程。

**Comment by lnlfps** [comment]
谢谢反馈，确实有这个问题，0.4.3版已经修复。从0.4.0版本开始，升级到webpack4和babel7，并做了大量的优化工作。
