### ISSUE TITLE
自定义Head问题

### ISSUE THREAD

**Issue by lyscms** [lnlfps/symph-joy#7]
1. 自定义Head即使加了key在多次render后依然重复，
2. 同时在页面渲染完成后，后端的请求还未完成，等到完成后再渲染都是客户端渲染，导致爬虫不能获取到来自客户端更新的数据，即SEO问题依然无法解决，eg：title，请问是我的用法不正确还是

**Comment by lnlfps** [comment]
1. 自定义header的bug已确定，将在下一版修复。
2. 请确保组件获取数据的逻辑在 async componentPrepare()中获取完成。https://lnlfps.github.io/symph-joy/#/thinking-in-joy?id=componentprepare-%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F

使用时遇到问题可在qq群里直接讨论，或者直接qq联系，这样交流更快捷些。

**Comment by lyscms** [comment]
问题已经解决了，不紧急，这里提问有记录，也可以帮助其他人，非常感谢，是在async componentPrepare() 中执行的，但是在服务端渲染的时候不能在之前增加副渲染内容，eg：loading，不然只会拿到loading的内容。
